baseURL: 'https://MikeLilley.github.io/'
languageCode: en-us
title: Michael Lilley
theme: PaperMod
params:
  showShareButtons: false
  defaultTheme: light
  disableScrollToTop: true
  UseHugoToc: true
  showtoc: true
  TocOpen: false
  env: production
  homeInfoParams:
    Title: About
    Content: >
      - This website is meant to serve as a digital CV as
        well as a place where I can write about subjects of interest to me. I am currently a PhD student in
        Computer Science at Kansas State University, with [Dr. Pascal Hitzler](https://people.cs.ksu.edu/~hitzler/) acting as my advisor.
        In addition, I work in the [Data Semantics Lab](https://daselab.cs.ksu.edu/) as a graduate research assistant.

      -

      - Prior to this, I was employed as the lead machine vision engineer at [USS Vision, Inc.](https://www.ussvision.com/), in Livonia, Michigan, where I
        led the design and implementation of software for bespoke real-time computer vision inspection systems for use in manufacturing plants. 
        Furthermore, I previously partook in research with the [Affective Computing and Multimodal Systems Lab](https://umdearborn.edu/cecs/departments/computer-and-information-science/laboratories)
        at the University of Michigan - Dearborn. I am also a graduate of this university with two undergraduate degrees in mathematics and computer science.
        Presently, I am most interested in topics surrounding neuro-symbolic systems, automated theorem proving, formal methods, and computer algebra systems.

      -

      - To contact me, please email [mblilley@ksu.edu](mailto:mblilley@ksu.edu).


  math: true

  socialIcons:
  - name: github
    title: GitHub
    url: "https://github.com/MikeLilley"
  - name: stackoverflow
    title: Stack Overflow
    url: "https://stackoverflow.com/users/22663758/michael-lilley"
  - name: linkedin
    title: LinkedIn
    url: "https://www.linkedin.com/in/michael-lilley-303936163/"

  fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

taxonomies:
  tag: tags

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: cv
      name: CV
      url: /cv/
      weight: 30

markup:
  goldmark:
    renderer:
      unsafe: true
